Feat: add switch widget lp9052
widgetti/solara pull request #185
Opened 2023-06-30 02:12 UTC by lp9052

add switch widget

see #174

2023-06-30 02:49 UTC, lp9052 commented
Do we have permission to rerun failed test?

2023-06-30 08:54 UTC, maartenbreddels commented
Thank you 🙏 

Apparently, you need to have write access for the repo to do that. I'm happy to restart it though

2023-06-30 08:58 UTC, maartenbreddels requested changes
Just a few minor points that would make this PR even more perfect 👍

2023-06-30 08:58 UTC, maartenbreddels commented on solara/components/switch.py
> +    style: str = None,
See bc81d7d93a608438674118afb0f27183de956afd for how we prefer the style argument

Please also add classes.

2023-06-30 08:58 UTC, maartenbreddels commented on solara/components/switch.py
> +    children = []
See https://github.com/widgetti/solara/blob/6934ee5108ad2a05d10a50ae8b3ad16dcca22fb4/solara/components/button.py#L11 for how we can support any child in addition to a label argument

2023-06-30 12:04 UTC, lp9052 commented
Thanks Maarten. 

I guess checkbox is one of the earlier piece that doesn't have all the new styles. All the enhancements make sense to me. I shall  update checkbox too. I'll start a new PR for checkbox.

2023-06-30 14:27 UTC, maartenbreddels commented
> I guess checkbox is one of the earlier piece that doesn't have all the new styles. All the enhancements make sense to me. I shall update checkbox too. I'll start a new PR for checkbox.

indeed, and that would be great!

> one small concern, we are passing `[]` as default parameter, it's mutable.

Yes, that's also something I usually frown upon... we are using that in many places because it also keeps the typing simpler so lets stick to it for now and if we change it, we'll do it throughout the whole codebase.

2023-06-30 14:33 UTC, lp9052 commented
hmmm, the testing suit seems somewhat unstable. 

also I want to open up an issue about unit test doesn't all pass out of the box.

it requires some other packages as solar enterprise, etc.

2023-06-30 14:36 UTC, maartenbreddels commented
Hmm, it's been a while since that test failed. Before we saw that one fail more often, see https://github.com/widgetti/solara/issues/131 for some comments/clues.
The integration test also has 1 flakey test.

2023-06-30 14:43 UTC, lp9052 commented
> Hmm, it's been a while since that test failed. Before we saw that one fail more often, see #131 for some comments/clues.
> The integration test also has 1 flakey test.

it's a quite interesting issue. I always like to see coverage info. And in my opinion 100% coverage is a must if we want to push this project further and accept more contributors

2023-06-30 14:48 UTC, maartenbreddels commented
I agree. A possible option might be to explicitly set `intrusive_cancel` in https://solara.dev/api/use_thread and only test that intrusive_cancel feature separately. 
Still, I find it really suspicious/odd that even after 10 seconds it does not finish the thread execution. I've stared at this failure many times and thought about it many times, but it might need a fresh pair of eyes.

2023-07-01 06:23 UTC, maartenbreddels approved these changes
💯

2023-07-02 08:47 UTC, maartenbreddels commented
There are 2 few missing I think
TODO:
 - [ ] Add to solara/website/pages/api/__init__.py
 - [ ] Add a gif 

I'm happy to pick this up if this is too much to ask. But this would also make this PR a nice template for new components.

2023-07-02 13:11 UTC, lp9052 commented
> There are 2 few missing I think
> 
> TODO:
> 
>  - [ ] Add to solara/website/pages/api/__init__.py
> 
>  - [ ] Add a gif to solara/website/public/api/
> 
> 
> 
> I'm happy to pick this up if this is too much to ask. But this would also make this PR a nice template for new components.

Give me a day or two. I might run into problem for gif. But I'll let you know. Thanks.

2023-07-11 03:18 UTC, lp9052 commented
Added these two pieces per suggestion.

2023-07-19 18:37 UTC, lp9052 commented
@maartenbreddels

2023-07-20 14:20 UTC, merged

2023-07-20 14:20 UTC, maartenbreddels commented
Thank you! 🙏