docs: added documentation for hooks
widgetti/solara pull request #372
Opened 2023-11-10 16:43 UTC by iisakkirotko

Added documentation for `use_effect`, `use_memo`, and improved the documentation of `use_thread`

2023-11-10 16:43 UTC, iisakkirotko commented
Current dependencies on/for this PR:
* master
  * **PR #372** <a href="https://app.graphite.dev/github/pr/widgetti/solara/372?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/widgetti/solara/372?utm_source=stack-comment).

2023-11-14 08:29 UTC, maartenbreddels requested changes
small comments, let me know if they make sense

2023-11-14 08:29 UTC, maartenbreddels commented on solara/website/pages/api/use_memo.md
> +`use_memo` stores ([memoize](/api/memoize)) the function return on first render, and then excludes it from being re-executed, except when one of the `dependencies` changes. `dependencies` can take th
```suggestion
`use_memo` stores ([memoize](https://en.wikipedia.org/wiki/Memoization)) the function return on first render, and then excludes it from being re-executed, except when one of the `dependencies` changes. `dependencies` can take the value `None`, in which case dependencies are automatically obtained from nonlocal variables. If an empty list is passed as `dependencies` instead, the function is only executed once over the entire lifetime of the component.

Not to be confused with [memorize](https://solara.dev/api/memoize) which can cache multiple return values and which can be used outside of component.
```

2023-11-14 08:31 UTC, iisakkirotko commented on solara/website/pages/api/use_memo.md
> +`use_memo` stores ([memoize](/api/memoize)) the function return on first render, and then excludes it from being re-executed, except when one of the `dependencies` changes. `dependencies` can take th
Not to be confused indeed.

2023-11-15 08:53 UTC, merged

2023-11-15 08:53 UTC, maartenbreddels commented
Thank you 🙏