feat: `enter_only` option for `InputText`
widgetti/solara pull request #376
Opened 2023-11-13 08:06 UTC by iisakkirotko

Previously `on_value` would be triggered whenever enter was pressed or `InputText` lost focus. Now, when `enter_only = True`, losing focus will not trigger this.

2023-11-13 08:06 UTC, iisakkirotko commented
Current dependencies on/for this PR:
* master
  * **PR #376** <a href="https://app.graphite.dev/github/pr/widgetti/solara/376?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/widgetti/solara/376?utm_source=stack-comment).

2023-11-13 15:19 UTC, iisakkirotko commented
> I think we should have this feature, but I wonder if we should have a different API. What about update_events=["blur", "keyup.enter"] as default arguments? This also allows a user to use "keyup.shift.enter" for instance. @mariobuikhuizen ?

Sounds like a good idea. We could then also support an arbitrary number of events as triggers. We should then also properly document the bug that causes only one event of a type to be picked up (unless that was fixed and I've forgotten).

2023-11-14 08:06 UTC, maartenbreddels requested changes
I think we don't need the overload anymore, and the docstring needs change.

Weird btw, that mypy didn't complain about the overload arguments not matching the function arguments.

2023-11-14 08:13 UTC, iisakkirotko commented
> I think we don't need the overload anymore, and the docstring needs change.

Should be fixed now

2023-11-15 08:55 UTC, merged

2023-11-15 08:55 UTC, maartenbreddels commented
I think this is very useful for https://github.com/widgetti/solara/pull/341 as well, such that we can bind to shift-enter