feat: Move from assets in package to s3 bucket
widgetti/solara pull request #462
Opened 2024-01-12 13:06 UTC by iisakkirotko

2024-01-12 13:06 UTC, iisakkirotko commented
Current dependencies on/for this PR:
* `master`
  * **PR #462** <a href="https://app.graphite.dev/github/pr/widgetti/solara/462?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/widgetti/solara/462?utm_source=stack-comment).

2024-01-16 16:18 UTC, maartenbreddels requested changes

2024-01-16 16:18 UTC, maartenbreddels commented on solara/components/file_download.py
> +            solara.Image("https://dxhl76zpt6fap.cloudfront.net/public/beach.jpeg", width="200px")
```suggestion
            solara.Image("solara.dev/static/public/beach.jpeg", width="200px")
```

2024-01-16 16:18 UTC, maartenbreddels commented on solara/lab/components/menu.py
> +        image_url = "https://dxhl76zpt6fap.cloudfront.net/public/beach.jpeg"
```suggestion
        image_url = "https://solara.dev/static/public/beach.jpeg"
```

2024-01-16 16:18 UTC, maartenbreddels commented on solara/lab/components/menu.py
> +        image_url = "https://dxhl76zpt6fap.cloudfront.net/public/beach.jpeg"
```suggestion
        image_url = "https://solara.dev/static/public/beach.jpeg"
```

2024-01-18 09:20 UTC, maartenbreddels commented on solara/components/file_download.py
> +            solara.Image("solara.dev/static/public/beach.jpeg", width="200px")
```suggestion
            solara.Image("https://solara.dev/static/public/beach.jpeg", width="200px")
```

2024-01-18 09:21 UTC, maartenbreddels approved these changes

2024-01-18 09:21 UTC, maartenbreddels commented on solara/lab/components/menu.py
> +        image_url = "https://solara.dev/static/public/beach.jpeg"
```suggestion
        image_url = "/static/public/beach.jpeg"
```

2024-01-18 09:21 UTC, maartenbreddels commented on solara/lab/components/menu.py
> +        image_url = "https://solara.dev/static/public/beach.jpeg"
```suggestion
        image_url = "/static/public/beach.jpeg"
```

2024-01-18 09:41 UTC, merged