fix: Mermaid and Math rendering in Jupyter Lab and VSCode
widgetti/solara pull request #480
Opened 2024-01-24 12:05 UTC by iisakkirotko

Should fix https://github.com/widgetti/solara/issues/175, and partially fix https://github.com/widgetti/solara/issues/446

2024-01-24 12:06 UTC, iisakkirotko commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/widgetti/solara/480?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #479** <a href="https://app.graphite.dev/github/pr/widgetti/solara/479?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #480** <a href="https://app.graphite.dev/github/pr/widgetti/solara/480?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/widgetti/solara/480?utm_source=stack-comment).

2024-01-29 13:54 UTC, maartenbreddels reviewed
Lets go with the changes we discussed over a call, and keep the katex part in

2024-01-29 13:54 UTC, maartenbreddels commented on packages/solara-widget-manager/package.json
> +    "mermaid": "^8.6.4"
```suggestion
```

2024-01-29 13:54 UTC, maartenbreddels commented on packages/solara-widget-manager/src/mermaid.ts
> +}
```suggestion
```

2024-01-29 13:54 UTC, maartenbreddels commented on packages/solara-widget-manager8/package.json
> +    "mermaid": "^8.6.4",
```suggestion
```

2024-01-29 13:54 UTC, maartenbreddels commented on solara/components/markdown.py
> +            return "https://cdn.jsdelivr.net/npm";
```suggestion
            return "{solara.server.settings.assets.cdn!r}";
```

2024-01-29 13:54 UTC, maartenbreddels commented on solara/components/markdown.py
> +            if vscode
```suggestion
            if solara.server.settings.assets.proxy
```

2024-01-29 13:54 UTC, maartenbreddels commented on solara/components/markdown.py
> +    return v.VuetifyTemplate.element(template=_markdown_template(html, style, vscode=VSCODE_PID is not None)).key(hash)
```suggestion
    return v.VuetifyTemplate.element(template=_markdown_template(html, style).key(hash)
```

2024-01-29 13:54 UTC, maartenbreddels commented on solara/components/markdown.py
> +def _markdown_template(html, style="", vscode=False):
```suggestion
def _markdown_template(html, style="",):
```

2024-01-30 09:42 UTC, maartenbreddels commented
See https://github.com/widgetti/solara/pull/487 and https://github.com/widgetti/solara/pull/488 for the refactor based on our discussions yesterday.

2024-02-09 12:50 UTC, maartenbreddels requested changes
After a small change we can merge I think. Surprised it does not fail the build on the renderMermaid actually!

2024-02-09 12:50 UTC, maartenbreddels commented on packages/solara-vuetify-app/src/solara.js
> +export { RenderMimeRegistry, WidgetManager, connectKernel, extendedRendererFactories, renderMathJax, renderMermaid, shutdownKernel } from '@widgetti/solara-widget-manager';
renderMermaid shouldn't be there anymore right?

2024-02-09 12:50 UTC, maartenbreddels commented on packages/solara-vuetify3-app/src/solara.js
> +export { RenderMimeRegistry, WidgetManager, connectKernel, extendedRendererFactories, renderMathJax, renderMermaid, shutdownKernel } from '@widgetti/solara-widget-manager';
same here

2024-02-09 15:59 UTC, merged