feat: support theming solara
widgetti/solara pull request #494
Opened 2024-02-05 13:36 UTC by iisakkirotko

2024-02-05 13:36 UTC, iisakkirotko commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/widgetti/solara/494?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #471** <a href="https://app.graphite.dev/github/pr/widgetti/solara/471?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #455** <a href="https://app.graphite.dev/github/pr/widgetti/solara/455?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #461** <a href="https://app.graphite.dev/github/pr/widgetti/solara/461?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #494** <a href="https://app.graphite.dev/github/pr/widgetti/solara/494?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
          * **PR #495** <a href="https://app.graphite.dev/github/pr/widgetti/solara/495?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #473** <a href="https://app.graphite.dev/github/pr/widgetti/solara/473?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #474** <a href="https://app.graphite.dev/github/pr/widgetti/solara/474?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #452** <a href="https://app.graphite.dev/github/pr/widgetti/solara/452?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/widgetti/solara/494?utm_source=stack-comment).

2024-02-14 08:41 UTC, maartenbreddels reviewed
I think this is going to be super cool!
Mostly worried about the naming, and maybe the theming.vue can be cleaned up a bit by using computed properties instead of using the clicks directly (difficult to follow).
(e.g. using a .is_auto() { return ...} )

2024-02-14 08:41 UTC, maartenbreddels commented on solara/lab/components/theming.vue
> +            if (localStorage.getItem('theme.variant')) {
```suggestion
            if (localStorage.getItem(':solara:theme.variant')) {
```
Shall we prefix it with something like this? Other prefix ideas are welcome :)
This reduces the chance of future name collisions with user chosen names

2024-02-14 08:41 UTC, maartenbreddels commented on solara/server/app.py
> +            theme.dark_effective = dark
```suggestion
            # While this usually gets set from the frontend, in solara (server) we want to know this directly at the first
            # render. Also, using the same trait allows us to write code which works on all widgets platforms, instead
            # or using something different when running under solara server
            theme.dark_effective = dark
```

2024-02-14 08:41 UTC, maartenbreddels commented on solara/website/pages/api/theming.py
> +Two themes are provided by default: light and dark.
I suggest we change the wording to say, 'theme; and 'dark', and in the settings it's `solara_theme_dark`. I think nobody knows what 'variant' means without spending brain cycles.
Also, does vuetify 3 change this?

2024-02-19 13:07 UTC, iisakkirotko commented on solara/website/pages/api/theming.py
> +Two themes are provided by default: light and dark.
`Vuetify supports both light and dark variants of the Material Design spec` Is what vuetify says in vuetify 2. In vuetify 3 it seems like they've gotten rid of the word variant, there the page says that they support two themes, light and dark. I think it's probably best for us to adopt the language from vuetify 3.

2024-02-21 10:11 UTC, maartenbreddels requested changes
Looking good.
I think we should remove totally the `variant_user_selectable` and change
```
class ThemeSettings(BaseSettings):
    variant: ThemeVariant = ThemeVariant.light
```

to
```
class ThemeSettings(BaseSettings):
    dark: ThemeVariant = ThemeVariant.light
```

To make it backward compatible, we should check if `SOLARA_THEME_VARIANT` is set, and make theme.dark reflect that.

Also, think about how this plays with the cmd line arg `"--theme-variant`. Not sure how we should expose it with the rename, `--dark=dark` seems a bit odd.
This could be a reason to keep the name variant, let me know what you think

2024-02-23 16:06 UTC, merged