ci: use env file instead of set_output
widgetti/solara pull request #579
Opened 2024-04-02 12:27 UTC by iisakkirotko

Although the removal of set_output has been delayed, it will still likely happen at some point. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for details

2024-04-02 12:27 UTC, iisakkirotko commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/widgetti/solara/579?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#579** <a href="https://app.graphite.dev/github/pr/widgetti/solara/579?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#578** <a href="https://app.graphite.dev/github/pr/widgetti/solara/578?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @iisakkirotko and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-04 08:51 UTC, maartenbreddels requested changes
only errors you spotted yourself :)

2024-04-04 08:51 UTC, maartenbreddels commented on .github/workflows/test.yaml
> +        if: github.event_name != 'schedule' && steps.install_no_lock.outputs.LOCKS_EXIST == 'true'
```suggestion
        if: github.event_name != 'schedule' && steps.prepare.outputs.LOCKS_EXIST == 'true'
```

2024-04-04 08:51 UTC, maartenbreddels commented on .github/workflows/test.yaml
> +        if: steps.cache-js-bundle-v2.outputs.cache-hit != true
```suggestion
        if: steps.cache-js-bundle-v2.outputs.cache-hit != 'true'
```

2024-04-04 08:51 UTC, maartenbreddels commented on .github/workflows/test.yaml
> +        if: steps.cache-js-bundle-v2.outputs.cache-hit != true
```suggestion
        if: steps.cache-js-bundle-v2.outputs.cache-hit != 'true'
```

2024-04-05 12:20 UTC, maartenbreddels approved these changes

2024-04-05 12:21 UTC, iisakkirotko commented
### Merge activity

* **Apr 5, 8:21 AM EDT**: @iisakkirotko started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/widgetti/solara/579).

2024-04-05 12:24 UTC, merged