Adding documentation to details component
widgetti/solara pull request #586
Opened 2024-04-08 11:13 UTC by mikegiann01

2024-04-08 11:15 UTC, mikegiann01 commented
This is about issue #222

2024-04-08 11:46 UTC, iisakkirotko requested changes
Hi @mikegiann01!

Thanks for the PR! The code quality errors should be easy to fix. Could you run 
`pip install pre-commit`
followed by
`pre-commit install`
This should automatically apply the formatting that pre-commit is complaining about when you try to run `git commit`. 

I also notice that `solara.Details` isn't present in the documentation right now. Would you like to also create a page for it in there? You can take a look at [`solara/website/pages/documentation/components/layout/card.py`](https://github.com/widgetti/solara/blob/master/solara/website/pages/documentation/components/layout/card.py) to see how it's done. Let me know here or on Discord if you have any questions!

2024-04-08 11:46 UTC, iisakkirotko commented on solara/components/details.py
> +    """
I think these should be moved to be right under the `def Details` Line

2024-04-08 12:13 UTC, mikegiann01 commented
Thanks for the response! I will follow your istructions and i will let you know on the process. About the documentation on the website i am very interested on working on this, i will check it out and i will let you know.

2024-04-10 11:37 UTC, mikegiann01 commented
Hello!! I have some upadates, I followed your instructions and i reached an impasse(shown in the picture):
<img width="567" alt="error" src="https://github.com/widgetti/solara/assets/149574350/6b31bd43-31f6-4759-abe5-95c695733179">
Could you maybe pinpoint what im doing wrong?

2024-04-12 15:21 UTC, iisakkirotko commented
Hey @mikegiann01!

I rebased the branch, so you could pull and try committing again. If that doesn't work, try upgrading flake8, or uninstalling and reinstalling pre-commit. (`pre-commit clean`, or `pre-commit uninstall` and `pre-commit install`)

2024-04-18 07:06 UTC, iisakkirotko requested changes
Hi @mikegiann01!

Looks like you're still having issues with pre-commit. It seems like the config file (`.pre-commit-config.yaml`) in your fork has been reset to a state from before some recent changes, which means that the code is being judged against different guidelines on your machine than online in our repository. I think this should be fixed with the following stes:
- reset `.pre-commit-config.yaml` to the state it is in the master branch of our repo
- run `pre-commit uninstall && pre-commit install` to install pre-commit

Other changes I'd like to see before merging this:
- remove the newly added pre-commit config files (`solara/.pre-commit-config.yaml`, etc.)
- squash the current 6 commits down to one or two (using, for example, `git rebase -i HEAD~6`)

2024-04-18 07:20 UTC, mikegiann01 commented
Okay thank you for the response!! Sorry for the number of commits and the
way i ve been using the platform , I am still trying to learn.

Στις Πέμ 18 Απρ 2024 στις 10:06 π.μ., ο/η Iisakki Rotko <
***@***.***> έγραψε:

> ***@***.**** requested changes on this pull request.
>
> Hi @mikegiann01 <https://github.com/mikegiann01>!
>
> Looks like you're still having issues with pre-commit. It seems like the
> config file (.pre-commit-config.yaml) in your fork has been reset to a
> state from before some recent changes, which means that the code is being
> judged against different guidelines on your machine than online in our
> repository. I think this should be fixed with the following stes:
>
>    - reset .pre-commit-config.yaml to the state it is in the master
>    branch of our repo
>    - run pre-commit uninstall && pre-commit install to install pre-commit
>
> Other changes I'd like to see before merging this:
>
>    - remove the newly added pre-commit config files (
>    solara/.pre-commit-config.yaml, etc.)
>    - squash the current 6 commits down to one or two (using, for example, git
>    rebase -i HEAD~6)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/widgetti/solara/pull/586#pullrequestreview-2008027640>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDVFFTWFTGZFP23FZBHVMEDY55WHNAVCNFSM6AAAAABF4PXF2KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMBYGAZDONRUGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-19 18:21 UTC, closed without merging