feat: Allow FileBrowser to show folders first
widgetti/solara pull request #59
Opened 2023-04-07 15:09 UTC by Jhsmit

This PR adds a boolean `folders_first` to the `FileBrowser`, which makes folders appear first in the sorting.

Also fixes a bug where the default filter for `list_dir` was the default built-in `filter`

2023-04-19 13:16 UTC, maartenbreddels requested changes
Nice, thank you!
I think it's better we sort tuples (not a related thing, but lets do it right directly).
Also, we choose to use 'directory' instead of 'folders'
Hope you agree

2023-04-19 13:16 UTC, maartenbreddels commented on solara/components/file_browser.py
> +def list_dir(path, filter: Callable[[Path], bool] = lambda x: True, folders_first: bool = False) -> List[dict]:
```suggestion
def list_dir(path, filter: Callable[[Path], bool] = lambda x: True, directory_first: bool = False) -> List[dict]:
```

2023-04-19 13:16 UTC, maartenbreddels commented on solara/components/file_browser.py
> +            return str(int(folders_first)) + item["name"].lower()
```suggestion
            return (folders_first, item["name"].lower())
```

2023-04-19 13:16 UTC, maartenbreddels commented on solara/components/file_browser.py
> +            return str(int(not folders_first)) + item["name"].lower()
```suggestion
            return (not folders_first, item["name"].lower())
```

2023-04-19 13:16 UTC, maartenbreddels commented on solara/components/file_browser.py
> +     * `folders_first`: If `True` folders are shown before files. Default: `False`.
```suggestion
     * `directory_first`: If `True` directories are shown before files. Default: `False`.
```

2023-04-19 13:40 UTC, Jhsmit commented
I agree, I tried tuples for sorting but it didnt works as I expected. 
But now it seems to work and it makes it much cleaner. 

Question: should the default value for `directory_first` be `True`, since that is the default on windows?
Also it is my preferred behavior, but if we change it its a 'breaking change'

2023-04-21 11:47 UTC, maartenbreddels commented
Yeah, it would be breaking behaviour. Lets keep it as it is.

2023-04-21 11:47 UTC, maartenbreddels approved these changes

2023-05-17 13:17 UTC, merged

2023-05-17 13:18 UTC, maartenbreddels commented
Thank you Jochem!