Feature: InputDate and InputDateRange Enhancements
widgetti/solara pull request #672
Opened 2024-06-06 19:58 UTC by brian-c-ogorman

# Overview

This change adds a few enhancements to the `InputDate` and `InputDateRange` components:

- Adds support for controlling the minimum/maximum allowed dates.
- Adds support for a date picker that has monthly granularity.
- Adds support for sorting the selected dates (for the `InputDateRange` component only).

See [here](https://github.com/widgetti/solara/issues/653) for the full discussion.

## Usage

### Daily granularity, with limits the min/max allowed date

Using the `min_date` and `max_date` parameters to limit selection to dates in the next two weeks:

```python
import datetime as dt
import solara

@solara.component
def Page():
    min_date = dt.date.today()
    max_date = min_date + dt.timedelta(days=14)

    selected_date = solara.use_reactive(min_date)
    solara.lab.InputDate(
        value=selected_date,
        min_date=min_date.isoformat(),
        max_date=max_date.isoformat(),
    )
    solara.Text(f"Selected date: {selected_date.value}")

Page()
```

<img width="296" alt="image" src="https://github.com/widgetti/solara/assets/30533489/23fa11d2-fede-42f5-b454-f5f0377124a8">

### Monthly granularity, with limits on the min/max allowed date

Use `date_picker_type="month"` to have an input with monthly granularity:

```python
import datetime as dt
import solara

@solara.component
def Page():
    
    min_date = dt.date.today().replace(day=1)
    max_date = (min_date + dt.timedelta(days=62)).replace(day=1)

    selected_date = solara.use_reactive(min_date)
    
    solara.lab.InputDate(
        value=selected_date,
        min_date=min_date.isoformat(),
        max_date=max_date.isoformat(),
        date_picker_type="month",
    )
    solara.Text(f"Selected date: {selected_date.value}")
    
Page()
```
<img width="298" alt="image" src="https://github.com/widgetti/solara/assets/30533489/1fbbcb74-a684-4187-9abe-1868398ed0aa">

## Daily granularity, with limits the min/max allowed dates, where the output is sorted

Use `sort=True` to automatically sort the output in ascending order:

```python
import datetime as dt
import solara

@solara.component
def Page():
    min_date = dt.date.today()
    max_date = min_date + dt.timedelta(days=14)

    selected_date = solara.use_reactive((min_date, min_date + dt.timedelta(days=1)))
    solara.lab.InputDateRange(
        value=selected_date,
        min_date=min_date.isoformat(),
        max_date=max_date.isoformat(),
        sort=True,
    )
    solara.Text(f"Selected dates: {selected_date.value}")
    
Page()
```

### Monthly granularity, with limits the min/max allowed dates, where the output is sorted

Use `date_picker_type="month"` to have an input with monthly granularity and `sort=True` to automatically sort the output in ascending order:

```python
import datetime as dt
import solara

@solara.component
def Page():
    
    min_date = dt.date.today().replace(day=1)
    max_date = (min_date + dt.timedelta(days=62)).replace(day=1)

    selected_date = solara.use_reactive(
        (min_date, (min_date + dt.timedelta(days=30)).replace(day=1))
    )
    
    solara.lab.InputDateRange(
        value=selected_date,
        min_date=min_date.isoformat(),
        max_date=max_date.isoformat(),
        date_picker_type="month",
        sort=True,
    )
    solara.Text(f"Selected date: {selected_date.value}")
    
Page()
```

## Vuetify 3 Upgrade Path

From what I can tell, in Vuetify 3, the `min` and `max` parameters are still supported by the `VDatePicker` object (see [here](https://vuetifyjs.com/en/api/v-date-picker/#props)).

I don't see a clear example of a date picker with monthly granularity on the component documentation [here](https://vuetifyjs.com/en/components/date-pickers/). Based on the API, it looks like they have split the "Monthly Date Picker" into a separate component, called `VDatePickerMonth` (see [here](https://vuetifyjs.com/en/api/v-date-picker-month/#props)). There is also a `VDatePickerMonths` in the API (see [here](https://vuetifyjs.com/en/api/v-date-picker-months/#props)), though it appears to have fewer parameters -- I am not sure how that component differs from or `VDatePickerMonth`.

As a result, when upgrading to Vuetify 3, these components would probably be split into something like `InputDate`/`InputMonth` and `InputDateRange`/`InputMonthRange`, based on the `VDatePicker` and `VDatePickerMonth` components, respectively.

2024-06-10 10:04 UTC, iisakkirotko requested changes
Thanks a lot for the PR and detailed explanation @brian-c-ogorman! I only had one comment. I think it would also be good to squash the last two commits into one. Otherwise looks great!

2024-06-10 15:51 UTC, brian-c-ogorman commented on solara/lab/components/input_date.py
>      see <a href="https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes" target="_blank">the Python documentation</a>.
Ah, I didn't realize that the link was just in the wrong place 😆. I will remove the extra one.

2024-06-11 07:42 UTC, iisakkirotko approved these changes
Looks good to me. Thanks a lot for the PR!

2024-07-03 08:59 UTC, merged

2024-07-03 09:00 UTC, maartenbreddels commented
Awesome work @brian-c-ogorman !
Thank you @iisakkirotko as well for the review.

We plan to release this soon, today maybe even.

2024-07-03 09:37 UTC, iisakkirotko commented
And it's out :)