docs: update state management documentation
widgetti/solara pull request #781
Opened 2024-09-10 09:45 UTC by maartenbreddels

2024-09-10 10:30 UTC, iisakkirotko requested changes

2024-09-10 10:30 UTC, iisakkirotko commented on solara/website/pages/documentation/getting_started/content/05-fundamentals/50-state-management.md
> +If you do need state that is specific to a component, you should use [`solara.use_reactive`](/documentation/api/hooks/use_reactive) hook. These hooks allow you to create local state variables that ar
```suggestion
If you do need state that is specific to a component, you should use [`solara.use_reactive`](/documentation/api/hooks/use_reactive) hook. This hook allows you to create local state variables that are scoped to a specific component. This approach is useful when you want to encapsulate state within a component, making it self-contained and modular. Local state management is suitable for situations where state changes only affect the component and do not need to be shared across the application.
```

2024-09-10 10:30 UTC, iisakkirotko commented on solara/website/pages/documentation/getting_started/content/05-fundamentals/50-state-management.md
> +If we take the previous example and replace `use_reactive` by `use_reactive`, we get:
```suggestion
If we take the previous example and replace `use_reactive` by `use_state`, we get:
```

2024-09-10 10:30 UTC, iisakkirotko commented on solara/website/pages/documentation/getting_started/content/05-fundamentals/50-state-management.md
> +However, many objects in Python are mutable, including lists and dictionaries or user defined classes. This means that you can change the value of a list, dictionary, or user defined class in place w
```suggestion
However, many objects in Python are mutable, including lists, dictionaries, and potentially user defined classes. This means that you can change the value of a list, dictionary, or user defined class in place without creating a new object.
```

2024-09-10 10:30 UTC, iisakkirotko commented on solara/website/pages/documentation/getting_started/content/05-fundamentals/50-state-management.md
> +Using reactive variables is a powerful way to manage state in your Solara applications. However, as your application grows, you may find that you need a more structured way to manage your state..
```suggestion
Using reactive variables is a powerful way to manage state in your Solara applications. However, as your application grows, you may find that you need a more structured way to manage your state.
```

2024-09-11 10:58 UTC, maartenbreddels commented on solara/website/pages/documentation/getting_started/content/05-fundamentals/10-components.md
> +In this example, we define a function called `on_button_click` that will be executed when the button is clicked. In the `MyInteractiveButton` function, we create a Button component and set the `on_cl
I agree, I think a follow document for more advanced component fundamentals should be added, and then we'll review this. Good point.

2024-09-11 14:30 UTC, JovanVeljanoski commented on solara/website/pages/documentation/getting_started/content/05-fundamentals/50-state-management.md
> +Or user defined classes, like a Panda DataFrame.
```suggestion
Or user defined classes, like a Pandas DataFrame.
```

2024-09-11 15:37 UTC, maartenbreddels commented on solara/website/pages/documentation/getting_started/content/05-fundamentals/50-state-management.md
> +Or user defined classes, like a Panda DataFrame.
Thanks!

2024-09-12 11:57 UTC, merged