Added a httponly option for HTMLResponse.set_cookie
widgetti/solara pull request #876
Opened 2024-11-25 07:45 UTC by lopezvoliver

Following the discussion in #799, I added an option configurable through an environment variable `SOLARA_SESSION_HTTP_ONLY`, and passing this to the `httponly` option in [HTMLResponse](https://www.starlette.io/responses/). 

As discussed, this change is backwards compatible because it defaults to False.

Here we can verify the httpOnly attribute of the `solara-session-id` cookie using Developer tools:

![image](https://github.com/user-attachments/assets/c7c7ef2f-b852-4fd7-8e46-a5b7507ce04d)

and here's another screenshot showing the behavior when setting the environment variable `SOLARA_SESSION_HTTP_ONLY=True`:

![image](https://github.com/user-attachments/assets/6a839d2f-9295-45c5-9ab7-ad2361939958)

Note that the cookie no longer appears in `document.cookie`. 

Thus, this PR makes it possible for a solara-based application to comply with [cwe 402](https://cwe.mitre.org/data/definitions/402.html)

2024-11-25 09:04 UTC, iisakkirotko approved these changes
Looks good to me. Thanks a lot for the PR @lopezvoliver!

2024-11-26 09:30 UTC, maartenbreddels requested changes
Awesome, I think we can make it a bit simpler even, what do you think?

2024-11-26 09:30 UTC, maartenbreddels commented on solara/server/settings.py
> +    http_only: Optional[bool] = None
```suggestion
    http_only: bool = False
```

I think we can do it like this. The reason https_only is 'tri-state' is that we do some checks when it is not explicitly set.

2024-11-26 13:53 UTC, lopezvoliver commented
> Awesome, I think we can make it a bit simpler even, what do you think?

Yes, and this is also consistent with the default False value in [starlette](https://github.com/encode/starlette/blob/13d0c1fbcdb6c6f861155beed352112843e57717/starlette/responses.py#L97).

2024-12-13 11:49 UTC, merged

2024-12-13 11:50 UTC, maartenbreddels commented
Thanks for your contribution @lopezvoliver !